yihong0618/xiaogpt

- xiaogpt.py
> Add execute mode to py script and fix config priority of MI_USER and MI_PASS(cli > env > default)

- README.md
- requirements.txt
详情见：https://github.com/yihong0618/xiaogpt/issues/56
> Update install README

- Dockerfile
- README.md
Fix the Dockerfile, and uploading the docker image
```
docker run -e OPENAI_API_KEY=sk-xxxxxx pengjianqing/xiaogpt:0.1 --account=xxxxx --password=xxxxxx --hardware=xxx --use_chatgpt_api
Running xiaogpt now, 用`帮我`开头来提问
以下是小爱的回答:  回答什么问题呢
以下是GPT的回答:
，，我会尽力以100字以内的回答来回答问题，但有时候可能需要更多的字数来做出更详
细的解释或回答。因此，我提供以下的回答：这取决于问题的具体复杂性和范围。一些问题
只需要几个单词回答，而其他问题则需要更详细和清晰的解释才能满足问题的需求。重要的
是要确保回答是准确和完整的，而不是简单地限制在字数上。
```
> fix the dockerfile

- xiaogpt.py
> add hardware LX5A

- xiaogpt.py
1. 用了一个简易的方法估算TTS耗时，减少网络请求
2. 把keyword和prompt加入可配置列表
3. `stop_if_xiaoai_is_playing` 目测不再需要，因为它会被后面的tts强制中止
> feat: a simple solution for mute xiaoai

- xiaogpt.py
> print question content to console

- xiaogpt.py
> feat: Support multiple keywords

- xiaogpt.py
> fix: turn to tuple for startswith

- xiaogpt/bot/__init__.py
- xiaogpt/bot/base_bot.py
- xiaogpt/bot/chatgpt_bot.py
- xiaogpt/bot/chatgptapi_bot.py
- xiaogpt/bot/gpt3_bot.py
- xiaogpt/cli.py
- xiaogpt/config.py
- xiaogpt/xiaogpt.py
> refactor: refactor the config reading

- README.md
- xiao_config.json.example
- xiaogpt/config.py
- xiaogpt/xiaogpt.py
> feat: Start and end continuous conversation

- .gitignore
- README.md
Build and upload the latest docker image
- https://hub.docker.com/repository/docker/pengjianqing/xiaogpt-arm64/
- https://hub.docker.com/repository/docker/pengjianqing/xiaogpt-x86/
> update the docker image

- README.md
- xiao_config.json.example
- xiaogpt/bot/base_bot.py
- xiaogpt/bot/chatgptapi_bot.py
- xiaogpt/bot/gpt3_bot.py
- xiaogpt/cli.py
- xiaogpt/config.py
- xiaogpt/utils.py
- xiaogpt/xiaogpt.py
> feat: support stream mode and switch to async request

- xiaogpt/cli.py
> fix: wrong value of boolean flags

- xiaogpt/xiaogpt.py
> fix: adjust sleep interval and setup pretty logger

- xiaogpt/xiaogpt.py
- Calculate the duration of tts and wait for proper time until TTS finishes
- ~It may be a bit slower because TTS convert and speak are done sequentially, might be improved by making them concurrent.~
> feat: Stream mode for edge tts

- xiaogpt/xiaogpt.py
> fix: hide the request log under non-verbose mode

- README.md
> README.md更新配置文件注释及使用

- README.md
- xiao_config.json.example
- xiaogpt/bot/base_bot.py
- xiaogpt/bot/chatgptapi_bot.py
- xiaogpt/bot/gpt3_bot.py
- xiaogpt/config.py
- xiaogpt/xiaogpt.py
> feat: Support overriding GPT options via config

- README.md
- xiao_config.json.example
- xiaogpt/bot/chatgptapi_bot.py
- xiaogpt/bot/gpt3_bot.py
- xiaogpt/cli.py
- xiaogpt/config.py
- xiaogpt/utils.py
- Add support for HTTP proxy configuration
- Improve CLI readability and modularization
> feat: Add HTTP proxy support for OpenAI API and CLI options

- Dockerfile
- README.md
- xiaogpt/utils.py
- xiaogpt/xiaogpt.py
> feat: add instruction to use edge TTS inside container

- xiaogpt/config.py
> fix: validate proxy only when it isn't blank

- xiaogpt/bot/chatgptapi_bot.py
- xiaogpt/bot/newbing_bot.py
> fix: overriding model parameter causes an error

- xiaogpt/xiaogpt.py
Fix the problem of multiple devices with the same hardware model and the issue of setting did only in config
> fix: did in config or multiple the same hardware

- README.md
- 一键运行.bat
> 添加windows 一键启动方式

- xiaogpt/bot/gpt3_bot.py
> Fix GPT3Bot.ask_stream

- xiaogpt/xiaogpt.py
Fixes #282
the session.get process without a timeout in poll_latest_ask task may hang.
add a time out of 15sec in total.
no hang found for 24 hour run.
> fix: add timeout when polling the latest ask

- xiaogpt/xiaogpt.py
用了一种比较 tricky 的方式解决，如果报错两次我们就重新 init
> fix: #282 #272

- README.md
add use in wsl have Notice at README.md
> docs(README.md): add use in wsl have Notice

- xiaogpt/bot/bard_bot.py
- xiaogpt/bot/base_bot.py
- xiaogpt/bot/chatgptapi_bot.py
- xiaogpt/bot/glm_bot.py
- xiaogpt/bot/gpt3_bot.py
- xiaogpt/bot/langchain_bot.py
- xiaogpt/bot/newbing_bot.py
- xiaogpt/langchain/callbacks.py
- xiaogpt/langchain/chain.py
- xiaogpt/xiaogpt.py
> feat: support memory and non-stream mode for langchain bot

- README.md
- xiao_config.json.example
add example for deployment_id and api_base
> add example for deployment_id and api_base

- README.md
> README Login faile的QA说明

- xiaogpt/cli.py
> fix: CLI default value overrides the config

- xiaogpt/langchain/chain.py
> fix: eliminate the deprecation warings from langchain

- README.md
- pdm.lock
- pyproject.toml
- xiao_config.json.example
- xiaogpt/bot/__init__.py
- xiaogpt/bot/qwen_bot.py
- xiaogpt/cli.py
- xiaogpt/config.py
> feat: support qwen

- xiaogpt/bot/bard_bot.py
- xiaogpt/bot/chatgptapi_bot.py
- xiaogpt/bot/gemini_bot.py
- xiaogpt/bot/glm_bot.py
- xiaogpt/bot/gpt3_bot.py
- xiaogpt/bot/newbing_bot.py
- xiaogpt/bot/qwen_bot.py
- xiaogpt/langchain/examples/email/mail_box.py
- xiaogpt/tts/openai.py
This can resolve issues like #438 in the future
> fix: lazy import bot-specific modules

- xiaogpt/bot/chatgptapi_bot.py
> fix: Update AOAI API version

- README.md
- pdm.lock
- pyproject.toml
- requirements.txt
> fix: use pdm-build-locked instead of pinning dependencies in pyproject.toml

- README.md
- pdm.lock
- pyproject.toml
- requirements.txt
- xiao_config.json.example
- xiaogpt/bot/__init__.py
- xiaogpt/bot/doubao_bot.py
- xiaogpt/cli.py
- xiaogpt/config.py
> feat: Support Doubao from Volcengine

- .gitignore
- README.md
- pdm.lock
- pyproject.toml
- requirements.txt
- xiaogpt/bot/__init__.py
- xiaogpt/bot/llama_bot.py
- xiaogpt/bot/moonshot_bot.py
- xiaogpt/bot/yi_bot.py
- xiaogpt/cli.py
- xiaogpt/config.py
- xiaogpt/xiaogpt.py
> feat: new bots openai like yi llama3 01

- xiaogpt/xiaogpt.py
Need https://github.com/yihong0618/MiService/pull/32
> WIP fix: can't stop when play background music

- pdm.lock
- pyproject.toml
- requirements.txt
- xiaogpt/utils.py
- xiaogpt/xiaogpt.py
> feat: detect language using lingua, instead of trusting LLM

- xiaogpt/bot/glm_bot.py
- xiaogpt/bot/qwen_bot.py
> fix: do not hardcode glm model

- xiaogpt/cli.py
- xiaogpt/config.py
- xiaogpt/tts/live.py
- xiaogpt/xiaogpt.py
> fix: make mp3 replayable

- xiao_config.yaml.example
- xiaogpt/bot/gemini_bot.py
- xiaogpt/config.py
尝试通过 config 来解决。
手头没有小爱能直接测试，未能保证质量，请见谅。
> feat: Customize Gemini model. #562

- pdm.lock
- pyproject.toml
- requirements.txt
- xiaogpt/bot/doubao_bot.py
- xiaogpt/config.py
修改豆包的接口调用方式，适配最新的V3接口。
配置文件里需要填写豆包的APIKEY(volc_api_key: "you_apikey")
> 修改豆包支持V3接口
